### ISSUE TITLE
Frontend monitoring

### ISSUE THREAD

**Issue by fbaig** [cybergis/iguide-web-v2#4]
**Problem**
There is no mechanism to detect whether any of the I-GUIDE services or website is down, not accessible or having any issues. All current detection is done manually which is not optimal and needs to be automated to mitigate failures and  increase efficiency.

**Potential Solution**
To detect whether the website is up or down, a simple python script can be executed on one of the VMs to ping every page of the website and generate email, Teams, SMS notifications in case of an error.

**Pull Requests**
ToDo ...

**Comment by rkalyanapurdue** [comment]
Perhaps have a widget on the I-GUIDE page that displays the status of various platform components (https://github.com/I-GUIDE/CI_Platform/issues/5). We can consider using status.io

**Comment by YunfanKang** [comment]
The monitoring for the frontedn website is in the [repo](https://github.com/I-GUIDE/Status-Monitoring-with-Upptime) and the monitoring page can be found at the [I-GUIDE Status monitoring page](https://i-guide.github.io/Status-Monitoring-with-Upptime/)

The notification will be sent through the #website-monitoring channel in the I-GUIDE slack.
